# Generated by Django 6.0.4 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['state', 'city'], name='optimizer_f_state_c4ef99_idx'), models.Index(fields=['retail_price'], name='optimizer_f_retail__d86a11_idx')],
            },
        ),
    ]
